USE DBProject
--1
--SELECT Nome, Categoria  FROM Empregado
--2
--SELECT * FROM Empregado WHERE Categoria = 'Programador'
--3
--SELECT Nome FROM Empregado WHERE Categoria = 'Programador'
--4
--SELECT Nome FROM Empregado WHERE Salario >= 200000 AND Salario <= 350000
--5
--SELECT Nome FROM Empregado WHERE Nome LIKE '%C%'
--6
--SELECT * FROM Projecto WHERE Designacao LIKE '%ria%'
--7
--SELECT DISTINCT DepNum FROM Empregado
--8
--SELECT ALL DepNum FROM Empregado
--9
--SELECT * FROM Empregado, Departamento WHERE Empregado.DepNum = Departamento.DepNum
--10
--SELECT Empregado.*, Departamento.Nome, Departamento.Local FROM Empregado, Departamento WHERE Empregado.DepNum = Departamento.DepNum
--11
--SELECT Empregado.*, Departamento.Nome, Departamento.Local FROM Empregado INNER JOIN Departamento ON Empregado.DepNum = Departamento.DepNum
--12
--SELECT Departamento.DepNum, Departamento.Nome, Empregado.EmpNum, Empregado.Nome FROM Departamento LEFT JOIN Empregado ON Empregado.DepNum = Departamento.DepNum
--13
--SELECT DISTINCT Atribuicao.EmpNum FROM Atribuicao WHERE Atribuicao.Funcao='coordenador' OR Atribuicao.Funcao='colaborador'
--14
--SELECT A.EmpNum FROM Atribuicao A WHERE A.Funcao='coordenador' INTERSECT SELECT A.EmpNum FROM Atribuicao A WHERE A.Funcao='colaborador'
--15
--SELECT Atribuicao.EmpNum FROM Atribuicao WHERE Atribuicao.Funcao='coordenador' EXCEPT SELECT Atribuicao.EmpNum FROM Atribuicao WHERE Atribuicao.Funcao='colaborador'
--16
--SELECT E.Nome FROM Empregado E, Atribuicao A WHERE E.EmpNum = A.EmpNum INTERSECT SELECT A.EmpNum FROM Atribuicao A WHERE A.ProjNum=1 INTERSECT SELECT A.EmpNum FROM Atribuicao A WHERE A.ProjNum=2 INTERSECT SELECT A.EmpNum FROM Atribuicao A WHERE A.ProjNum=3 INTERSECT SELECT A.EmpNum FROM Atribuicao A WHERE A.ProjNum=4
--17
--SELECT P.Designacao FROM Projecto P WHERE 
SELECT DISTINCT D.DepNum FROM Departamento D

--18
